<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MenuItem;
use App\Models\Dish;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menuItems = [
            ['MenuID' => 1, 'DishName' => 'Soep Ling Fa', 'ItemNumber' => 1, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kippensoep', 'ItemNumber' => 2, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tomatensoep', 'ItemNumber' => 3, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Haaienvinnensoep', 'ItemNumber' => 4, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Champignonsoep', 'ItemNumber' => 5, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Pekingsoep', 'ItemNumber' => 6, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Wan Tan Soep', 'ItemNumber' => 7, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Chinese Champignonsoep', 'ItemNumber' => 8, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Loempia Ling Fa', 'ItemNumber' => 10, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Loempia Compleet', 'ItemNumber' => 11, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Loempia met Kip', 'ItemNumber' => 12, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Loempia', 'ItemNumber' => 13, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Chinese mini loempia', 'ItemNumber' => 14, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Vegetarische mini loempia', 'ItemNumber' => 14, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Kroepoek', 'ItemNumber' => 15, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Casave Kroepoek', 'ItemNumber' => 15, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Pangsit Goreng', 'ItemNumber' => 16, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Pisang Goreng', 'ItemNumber' => 17, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Chinese Dim Sum', 'ItemNumber' => 18, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Sat&eacute; Babi', 'ItemNumber' => 19, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Sat&eacute; Ajam', 'ItemNumber' => 20, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Sat&eacute; Garnalen', 'ItemNumber' => 20, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Fong Mei Ha', 'ItemNumber' => 21, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Patat', 'ItemNumber' => 22, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tsa Siu Mai', 'ItemNumber' => 23, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Atjar', 'ItemNumber' => 24, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Witte Rijst', 'ItemNumber' => 25, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Grote pindasaus', 'ItemNumber' => 26, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kleine pindasaus', 'ItemNumber' => 27, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kippenpootje', 'ItemNumber' => 28, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Halve kip', 'ItemNumber' => 29, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kroket', 'ItemNumber' => 29, 'ExtraIdentifier' => 'H'],
            ['MenuID' => 1, 'DishName' => 'Frikandel', 'ItemNumber' => 29, 'ExtraIdentifier' => 'G'],
            ['MenuID' => 1, 'DishName' => 'Kleine Sambal', 'ItemNumber' => 180, 'ExtraIdentifier' => 'H'],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Goreng Ling Fa', 'ItemNumber' => 30, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Goreng met ei', 'ItemNumber' => 31, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Goreng speciaal', 'ItemNumber' => 32, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Goreng met sat&eacute;', 'ItemNumber' => 33, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Nasi Yeung Chow', 'ItemNumber' => 34, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Nasi Yeung Chow', 'ItemNumber' => 34, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Malay', 'ItemNumber' => 35, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi met kipfilet', 'ItemNumber' => 36, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi met varkensvlees', 'ItemNumber' => 37, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi met garnalen', 'ItemNumber' => 38, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi met ossenhaas', 'ItemNumber' => 39, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Babi Pangang, Foe Yong Hani en sat&eacute;', 'ItemNumber' => 40, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Babi Pangang, Tjap Tjoy en sat&eacute;', 'ItemNumber' => 41, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Babi Pangang, Koe Loe Yuk en sat&eacute;', 'ItemNumber' => 42, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Babi Pangang, Tau Sie Kai en sat&eacute;', 'ItemNumber' => 43, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Koe Loe Yuk, Foe Yong Hai en sat&eacute;', 'ItemNumber' => 44, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Koe Loe Yuk, Tjap Tjoy en sat&eacute;', 'ItemNumber' => 45, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai, Tjap Tjoy en sat&eacute;', 'ItemNumber' => 46, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai, Kip Kerrie en Sat&eacute;', 'ItemNumber' => 47, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen Ling Fa', 'ItemNumber' => 50, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen met varkensvlees', 'ItemNumber' => 51, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen met kipfilet', 'ItemNumber' => 52, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen met ossenhaas', 'ItemNumber' => 53, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen met garnalen', 'ItemNumber' => 54, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen Singapore-style', 'ItemNumber' => 55, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen met Cha Sieuw vlees', 'ItemNumber' => 56, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Chinese Bami Ling Fa', 'ItemNumber' => 57, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Chinese Bami met varkensvlees', 'ItemNumber' => 58, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Chinese Bami met kipfilet', 'ItemNumber' => 58, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Chinese Bami met Cha Sieuw-vlees', 'ItemNumber' => 58, 'ExtraIdentifier' => 'B'],
            ['MenuID' => 1, 'DishName' => 'Chinese Bami met garnalen', 'ItemNumber' => 58, 'ExtraIdentifier' => 'C'],
            ['MenuID' => 1, 'DishName' => 'Chinese Bami met ossenhaas', 'ItemNumber' => 58, 'ExtraIdentifier' => 'D'],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Rames Ling Fa', 'ItemNumber' => null, 'ExtraIdentifier' => 'M1'],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Rames', 'ItemNumber' => null, 'ExtraIdentifier' => 'M2'],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Rames speciaal', 'ItemNumber' => null, 'ExtraIdentifier' => 'M3'],
            ['MenuID' => 1, 'DishName' => 'Gado Gado', 'ItemNumber' => null, 'ExtraIdentifier' => 'M4'],
            ['MenuID' => 1, 'DishName' => 'Daging Smoor', 'ItemNumber' => null, 'ExtraIdentifier' => 'M5'],
            ['MenuID' => 1, 'DishName' => 'Daging Roedjak', 'ItemNumber' => null, 'ExtraIdentifier' => 'M6'],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai Ling Fa', 'ItemNumber' => 59, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai met varkensvlees', 'ItemNumber' => 60, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai met kipfilet', 'ItemNumber' => 61, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai met garnalen', 'ItemNumber' => 62, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai met krab', 'ItemNumber' => 63, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai met Cha Sieuw Vlees', 'ItemNumber' => 63, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Foe Yong Hai met ossenhaas', 'ItemNumber' => 63, 'ExtraIdentifier' => 'B'],
            ['MenuID' => 1, 'DishName' => 'Tjap Tjoy Ling Fa', 'ItemNumber' => 64, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tjap Tjoy met varkensvlees', 'ItemNumber' => 65, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tjap Tjoy met kipfilet', 'ItemNumber' => 66, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tjap Tjoy met ossenhaas', 'ItemNumber' => 67, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tjap Tjoy met garnalen', 'ItemNumber' => 68, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Babi Pangang', 'ItemNumber' => 70, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Babi Pangang in ketjapsaus', 'ItemNumber' => 71, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Cha Sieuw', 'ItemNumber' => 72, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Cha Sieuw in pikante saus', 'ItemNumber' => 73, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Geroosterde speenvarken', 'ItemNumber' => 74, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Koe Loe Yuk', 'ItemNumber' => 75, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Varkenshaas met kerriesaus', 'ItemNumber' => 76, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Varkenshaas met ketjapsaus', 'ItemNumber' => 77, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Varkenshaas met tomatensaus', 'ItemNumber' => 78, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Varkenshaas met champignons in knoflooksaus', 'ItemNumber' => 78, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Varkenshaas met Chinese champignons', 'ItemNumber' => 78, 'ExtraIdentifier' => 'B'],
            ['MenuID' => 1, 'DishName' => 'Varkenshaas met zwarte bonensaus', 'ItemNumber' => 79, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Varkenshaas met verse ananas in zoetzure saus', 'ItemNumber' => 79, 'ExtraIdentifier' => 'A'],
            ['MenuID' => 1, 'DishName' => 'Yu Sian Yuk', 'ItemNumber' => 79, 'ExtraIdentifier' => 'B'],
            ['MenuID' => 1, 'DishName' => 'SzeChuan Yuk', 'ItemNumber' => 79, 'ExtraIdentifier' => 'C'],
            ['MenuID' => 1, 'DishName' => 'Ajam Pangang', 'ItemNumber' => 80, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ajam Pangang in ketjapsaus', 'ItemNumber' => 81, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Koe Loe Kai', 'ItemNumber' => 82, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met kerriesaus', 'ItemNumber' => 83, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met champignons in knoflooksaus', 'ItemNumber' => 84, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met tomatensaus', 'ItemNumber' => 85, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met ketjapsaus', 'ItemNumber' => 86, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met broccoli in knoflooksaus', 'ItemNumber' => 87, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met Chinese champignons', 'ItemNumber' => 88, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met zwarte pepersaus', 'ItemNumber' => 89, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met verse ananas in zoetzure saus', 'ItemNumber' => 90, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kipfilet met zwarte pepersaus', 'ItemNumber' => 91, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tjieuw Yem Kai', 'ItemNumber' => 92, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Yao Koe Kai', 'ItemNumber' => 93, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Lychee Kai', 'ItemNumber' => 94, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Yu Sian Kai', 'ItemNumber' => 95, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Sze Chuan Kai', 'ItemNumber' => 96, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Kung Bao Kai', 'ItemNumber' => 97, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met champignons in knoflooksaus', 'ItemNumber' => 98, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met tomatensaus', 'ItemNumber' => 99, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met ketjapsaus', 'ItemNumber' => 100, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met broccoli', 'ItemNumber' => 101, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met Chinese champignons', 'ItemNumber' => 102, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met kerriesaus', 'ItemNumber' => 103, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met zwarte bonensaus', 'ItemNumber' => 104, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met zwarte pepersaus', 'ItemNumber' => 105, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Garnalen met chilisaus', 'ItemNumber' => 106, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Yu Sian Haa', 'ItemNumber' => 107, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tjieuw Yem Haa', 'ItemNumber' => 108, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tja Tai Haa', 'ItemNumber' => 109, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Sze Chuan Haa', 'ItemNumber' => 110, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met chanpignons in knoflooksaus', 'ItemNumber' => 111, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met tomatensaus', 'ItemNumber' => 112, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met ketjapsaus', 'ItemNumber' => 113, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met broccoli', 'ItemNumber' => 114, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met Chinese champignons', 'ItemNumber' => 115, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met kerriesaus', 'ItemNumber' => 116, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met zwarte bonensaus', 'ItemNumber' => 117, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Ossenhaas met zwarte pepersaus', 'ItemNumber' => 118, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Yu Sian Ngau Yuk', 'ItemNumber' => 119, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Sze Chuan Ngau Yuk', 'ItemNumber' => 120, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Visfilet met kerriesaus', 'ItemNumber' => 121, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Visfilet met oestersaus', 'ItemNumber' => 122, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Visfilet met zoetzure saus', 'ItemNumber' => 123, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Hong Shau Yu', 'ItemNumber' => 124, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Tjeuw Yem Yu', 'ItemNumber' => 125, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'San Sching Po', 'ItemNumber' => 126, 'ExtraIdentifier' => null],

            ['MenuID' => 1, 'DishName' => 'Geroosterde Peking Eend', 'ItemNumber' => null, 'ExtraIdentifier' => 'P1'],
            ['MenuID' => 1, 'DishName' => 'Peking Eend met verse ananas in zoetzure saus', 'ItemNumber' => null, 'ExtraIdentifier' => 'P2'],
            ['MenuID' => 1, 'DishName' => 'Peking Eend met Chinese champignons in oestersaus', 'ItemNumber' => null, 'ExtraIdentifier' => 'P3'],
            ['MenuID' => 1, 'DishName' => 'Yu Sian Ya', 'ItemNumber' => null, 'ExtraIdentifier' => 'P4'],
            ['MenuID' => 1, 'DishName' => 'Tiepan Ling Fa', 'ItemNumber' => null, 'ExtraIdentifier' => 'T1'],
            ['MenuID' => 1, 'DishName' => 'Tiepan Kai', 'ItemNumber' => null, 'ExtraIdentifier' => 'T2'],
            ['MenuID' => 1, 'DishName' => 'Tiepan San Yuk', 'ItemNumber' => null, 'ExtraIdentifier' => 'T3'],
            ['MenuID' => 1, 'DishName' => 'Tiepan Haa', 'ItemNumber' => null, 'ExtraIdentifier' => 'T4'],
            ['MenuID' => 1, 'DishName' => 'Tiepan Ngau Yuk', 'ItemNumber' => null, 'ExtraIdentifier' => 'T5'],
            ['MenuID' => 1, 'DishName' => 'Tau Fu Po', 'ItemNumber' => null, 'ExtraIdentifier' => 'V4'],
            ['MenuID' => 1, 'DishName' => 'Vegetarische Tjap Tjoy', 'ItemNumber' => null, 'ExtraIdentifier' => 'V1'],
            ['MenuID' => 1, 'DishName' => 'Lo Han Zhai', 'ItemNumber' => null, 'ExtraIdentifier' => 'V2'],
            ['MenuID' => 1, 'DishName' => 'Vegetarische Foe Yong Hai', 'ItemNumber' => null, 'ExtraIdentifier' => 'V3'],
            ['MenuID' => 1, 'DishName' => 'Frites, saté (2st.) en ei', 'ItemNumber' => null, 'ExtraIdentifier' => 'K1'],
            ['MenuID' => 1, 'DishName' => 'Frites, kippootje en ei', 'ItemNumber' => null, 'ExtraIdentifier' => 'K2'],
            ['MenuID' => 1, 'DishName' => 'Frites, mini loempia (2st.) en ei', 'ItemNumber' => null, 'ExtraIdentifier' => 'K3'],
            ['MenuID' => 1, 'DishName' => 'Kinder Bami of Nasi met saté (2st.) en ei', 'ItemNumber' => null, 'ExtraIdentifier' => 'K4'],
            ['MenuID' => 1, 'DishName' => 'Indische rijsttafel (voor 1 persoon)', 'ItemNumber' => null, 'ExtraIdentifier' => 'R1'],
            ['MenuID' => 1, 'DishName' => 'Indische rijsttafel<br>Vanaf 2 personen... Per persoon', 'ItemNumber' => null, 'ExtraIdentifier' => 'R2'],
            ['MenuID' => 1, 'DishName' => 'Chinese Indische Rijsttafel<br>Vanaf 4 personen... per persoon', 'ItemNumber' => null, 'ExtraIdentifier' => 'R3'],
            ['MenuID' => 1, 'DishName' => 'Chinese Rijsttafel<br>Vanaf 2 personen... per persoon', 'ItemNumber' => null, 'ExtraIdentifier' => 'R4'],
            ['MenuID' => 1, 'DishName' => 'Kantones Rijsttafel<br>Vanaf 2 personen... per persoon', 'ItemNumber' => null, 'ExtraIdentifier' => 'R5'],
            ['MenuID' => 1, 'DishName' => 'Sze Chuan Rijsttafel<br>Vanaf 2 personen... per persoon', 'ItemNumber' => null, 'ExtraIdentifier' => 'R6'],
            ['MenuID' => 1, 'DishName' => 'Buffet Menu A, per persoon', 'ItemNumber' => null, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Buffet Menu B, per persoon', 'ItemNumber' => null, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Bami of Nasi Goreng ipv rijst', 'ItemNumber' => null, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Mihoen Goreng ipv rijst', 'ItemNumber' => null, 'ExtraIdentifier' => null],
            ['MenuID' => 1, 'DishName' => 'Chinese Bami ipv rijst', 'ItemNumber' => null, 'ExtraIdentifier' => null],
        ];

        foreach ($menuItems as $menuItem) {
            $dish = Dish::where('DishName', $menuItem['DishName'])->first();
            if ($dish) {
                MenuItem::create([
                    'MenuID' => $menuItem['MenuID'],
                    'DishID' => $dish->DishID,
                    'ItemNumber' => $menuItem['ItemNumber'],
                    'ExtraIdentifier' => $menuItem['ExtraIdentifier']
                ]);
            }
        }
    }
}
